const ProjectConstants = { 
    DEFAULT_MIN_STAR_COUNT_PER_GALAXY: 10,
    DEFAULT_MAX_STAR_COUNT_PER_GALAXY: 100000,
    DEFAULT_NOMAD_PLANET_COEFICIENT: 0.1,
    DEFAULT_STAR_CLUSTER_COEFICIENT: 0.3,
    DEFAULT_MAX_MOON_COUNT_PER_PLANET: 10,
    DEFAULT_MIN_MOON_COUNT_PER_PLANET: 0,
    DEFAULT_MAX_PLANET_COUNT_PER_SYSTEM: 15,
    DEFAULT_MIN_PLANET_COUNT_PER_SYSTEM: 0,
    DEFAULT_MAX_STAR_COUNT_PER_SYSTEM: 2
}

module.exports = ProjectConstants;